"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-02-15 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hs_codes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=False),
        sa.Column('level', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=2), nullable=False),
        sa.Column('mfn_rate', sa.Float(), nullable=True),
        sa.Column('general_rate', sa.Float(), nullable=True),
        sa.Column('vat_rate', sa.Float(), nullable=True),
        sa.Column('consumption_tax', sa.Float(), nullable=True),
        sa.Column('unit', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_codes_code'), 'hs_codes', ['code'], unique=True)
    op.create_index(op.f('ix_hs_codes_country'), 'hs_codes', ['country'], unique=False)
    op.create_index(op.f('ix_hs_codes_id'), 'hs_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hs_codes_id'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_country'), table_name='hs_codes')
    op.drop_index(op.f('ix_hs_codes_code'), table_name='hs_codes')
    op.drop_table('hs_codes')
    # ### end Alembic commands ###